sudo: false

language: ruby

rvm:
  - 2.4.0

before_install:
  - gem update --system
  - gem install bundler

cache: bundler
script: bundle exec middleman build
deploy:
  local-dir: build
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
