sudo: false

language: ruby

rvm:
  - 2.3.1

cache: bundler
script: bundle exec middleman build --clean
deploy:
  local-dir: build
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
